src/web/Models/Vehicle.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace VehicleTracker.Models
{
    public class Vehicle
    {
        private String numberPlate;
        private String branchId;
        private String hardwareId;
        private String description;
        private String typeId;
        private String userEmail;
        private int deleted;
        private int writeHistory;

        [StringLength(20, ErrorMessage = "Tối đa 20 ký tự")]
        [Required(ErrorMessage = "Không để trống trường này")]
        [DataType(DataType.Text, ErrorMessage = "Dữ liệu phải là Text")]
        public string NumberPlate { get => numberPlate; set => numberPlate = value; }

        public string BranchId { get => branchId; set => branchId = value; }

        public string HardwareId { get => hardwareId; set => hardwareId = value; }

        [StringLength(200, ErrorMessage = "Tối đa 200 ký tự")]
        [Required(ErrorMessage = "Không để trống trường này")]
        [DataType(DataType.Text, ErrorMessage = "Dữ liệu phải là Text")]
        public string Description { get => description; set => description = value; }

        public string TypeId { get => typeId; set => typeId = value; }

        [StringLength(80, ErrorMessage = "Tối đa 80 ký tự")]
        [Required(ErrorMessage = "Không để trống trường này")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage = "Dữ liệu phải là Email")]
        public string UserEmail { get => userEmail; set => userEmail = value; }

        public int Deleted { get => deleted; set => deleted = value; }

        public int WriteHistory { get => writeHistory; set => writeHistory = value; }
    }
}

src/web/Models/VehicleType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace VehicleTracker.Models
{
    public class VehicleType
    {
        private String id;
        private String name;

        [StringLength(10, ErrorMessage = "Tối đa 10 ký tự")]
        [Required(ErrorMessage = "Không để trống trường này")]
        public string Id { get => id; set => id = value; }

        [StringLength(100, ErrorMessage = "Tối đa 100 ký tự")]
        [Required(ErrorMessage = "Không để trống trường này")]
        public string Name { get => name; set => name = value; }
    }
}

src/web/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using VehicleTracker.ViewModel;
using VehicleTracker.Helper;
using VehicleTracker.Models;
using Microsoft.AspNetCore.Http;

namespace VehicleTracker.Controllers
{
    public class VehicleController : Controller
    {
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("Admin") == null || HttpContext.Session.GetString("Admin") == String.Empty)
            {
                return RedirectToAction("Login", "Admin");
            }

            using (var client = new HttpClient())
            {
                try
                {
                    return View(await VehicleVM.GetAllVehicleAsync(client));
                }
                catch (Exception)
                {
                    return BadRequest(Lang.LANG_CONNECTION_PROBLEM);
                }
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(String numberPlate)
        {
            if (HttpContext.Session.GetString("Admin") == null || HttpContext.Session.GetString("Admin") == String.Empty)
            {
                return RedirectToAction("Login", "Admin");
            }

            using (var client = new HttpClient())
            {
                try
                {
                    return View(await VehicleVM.GetVehicleByNumberPlateAsync(client, numberPlate));
                }
                catch (Exception)
                {
                    return BadRequest(Lang.LANG_CONNECTION_PROBLEM);
                }
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    try
                    {
                        String _result = await VehicleVM.UpdateVehicleAsync(client, vehicle);
                        if (_result.Equals(ResultCode.DONE))
                        {
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            return BadRequest(Lang.LANG_UPDATE_PROBLEM);
                        }
                    }
                    catch (Exception)
                    {
                        return BadRequest(Lang.LANG_CONNECTION_PROBLEM);
                    }
                }
            }
            return View();
        }

        public async Task<IActionResult> Delete(string numberPlate)
        {
            using (var client = new HttpClient())
            {
                try
                {
                    String _result = await VehicleVM.DeleteVehicleAsync(client, numberPlate);
                    if (_result.Equals(ResultCode.DONE))
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return BadRequest(Lang.LANG_UPDATE_PROBLEM);
                    }
                }
                catch (Exception)
                {
                    return BadRequest(Lang.LANG_CONNECTION_PROBLEM);
                }
            }
        }
    }
}

src/web/Views/Vehicle/Edit.cshtml
@using VehicleTracker.Models
@using System.Net.Http
@using VehicleTracker.ViewModel
@model Vehicle
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div id="content">
    <header class="clearfix">
        <h2 class="page-title">
            Sửa thông tin xe đăng kí
        </h2>
    </header>
    <div class="content-inner">
        <div class="row">
            <div class="col-md-8">
                @using (Html.BeginForm())
                {
                    @Html.HiddenFor(model => model.WriteHistory)
                    <div class="edit-row">
                        <h3>Biển số xe</h3>
                        <p>Là chữ và số, tối đa 20 ký tự</p>
                        <div class="form-group">
                            <input type="text" id="NumberPlate" name="NumberPlate" class="form-control" title="" disabled placeholder="Id" value="@Model.NumberPlate">
                        </div>
                    </div>
                    <div class="edit-row">
                        <h3>Hãng xe</h3>
                        <p>Lựa chọn hãng xe</p>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-4">
                                    @{
                                        List<SelectListItem> lstItems = new List<SelectListItem>();
                                        using (var client = new HttpClient())
                                        {
                                            IList<Branch> _branchs = await BranchVM.GetAllBranchAsync(client);
                                            foreach(var branch in _branchs)
                                            {
                                                if(Model.BranchId == branch.Id)
                                                {
                                                    lstItems.Add(new SelectListItem
                                                    {
                                                        Text = branch.Name,
                                                        Value = branch.Id,
                                                        Selected = true
                                                    });
                                                }
                                                else
                                                {
                                                    lstItems.Add(new SelectListItem
                                                    {
                                                        Text = branch.Name,
                                                        Value = branch.Id
                                                    });
                                                }
                                            }
                                        }
                                        @Html.DropDownListFor(model => model.BranchId, lstItems, new { @class = "form-control" })
                                    }
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="edit-row">
                        <h3>Mã thiết bị</h3>
                        <p>Là chữ và số, tối đa 10 ký tự</p>
                        <div class="form-group">
                            <input type="text" id="HardwareId" name="HardwareId" class="form-control" title="" placeholder="Id" value="@Model.HardwareId">
                        </div>
                    </div>

                    <div class="edit-row">
                        <h3>Mô tả</h3>
                        <p>Là chữ và số, tối đa 200 ký tự</p>
                        <div class="form-group">
                            <input type="text" id="Description" name="Description" class="form-control" title="" placeholder="Id" value="@Model.Description">
                        </div>
                    </div>

                    <div class="edit-row">
                        <h3>Loại xe</h3>
                        <p>Lựa chọn loại xe</p>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-4">
                                    @{
                                        List<SelectListItem> lstItemsType = new List<SelectListItem>();
                                        using (var client = new HttpClient())
                                        {
                                            IList<VehicleType> _types = await VehicleTypeVM.GetAllVehicleTypeAsync(client);
                                            foreach (var type in _types)
                                            {
                                                if (Model.TypeId == type.Id)
                                                {
                                                    lstItemsType.Add(new SelectListItem
                                                    {
                                                        Text = type.Name,
                                                        Value = type.Id,
                                                        Selected = true
                                                    });
                                                }
                                                else
                                                {
                                                    lstItemsType.Add(new SelectListItem
                                                    {
                                                        Text = type.Name,
                                                        Value = type.Id
                                                    });
                                                }
                                            }
                                        }
                                        @Html.DropDownListFor(model => model.TypeId, lstItemsType, new { @class = "form-control" })
                                    }
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="edit-row">
                        <h3>Email người dùng</h3>
                        <p>Là chữ và số, tối đa 80 ký tự</p>
                        <div class="form-group">
                            <input type="text" id="UserEmail" name="UserEmail" class="form-control" title="" placeholder="Id" value="@Model.UserEmail">
                        </div>
                    </div>

                    <div class="edit-row">
                        <h3>Xóa?</h3>
                        <p>Chọn 1 nếu muốn xóa</p>
                        <div class="form-group">
                            <input type="number" id="Deleted" name="Deleted" class="form-control small-input" value="@Model.Deleted" min="0" max="1" step="1" required="required">
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary" value="Lưu thông tin" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>

src/web/Views/Vehicle/Index.cshtml
@using VehicleTracker.Models
@using System.Net.Http
@using VehicleTracker.ViewModel
@model List<Vehicle>
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="dashboard-con">
    <div class="row">
        <div class="col-md-12">
            <div class="admin-content-con clearfix">
                <header>
                    <div class="row">
                        <div class="col-md-4">
                            <h5>Danh sách các xe đã đăng ký</h5>
                        </div>
                        <div class="col-md-offset-4 col-md-4">
                            <a class="btn btn-primary pull-right" href="@Url.Action("RegVehicle", "Home")" role="button" target="_blank">Đăng ký xe mới</a>
                        </div>
                    </div>
                </header>

                <table class="table table-bordered" style="font-size: 15px;">
                    <thead>
                        <tr>
                            <th>Biển số xe</th>
                            <th>Hãng xe</th>
                            <th>Mã thiết bị</th>
                            <th>Loại xe</th>
                            <th>Mô tả</th>
                            <th>Email chủ xe</th>
                            <th><center>Xóa?</center></th>
                            <th><center>Trạng thái</center></th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @{
                            foreach (var vehicle in Model)
                            {
                                <tr>
                                    <td>@vehicle.NumberPlate</td>
                                    <td>
                                        @{
                                            using (var client = new HttpClient())
                                            {
                                                Branch _branch = await BranchVM.GetBranchByIdAsync(client, vehicle.BranchId);
                                                <span>@_branch.Name</span>
                                            }
                                        }
                                    </td>
                                    <td>@vehicle.HardwareId</td>
                                    <td>
                                        @{
                                            using (var client = new HttpClient())
                                            {
                                                VehicleType _type = await VehicleTypeVM.GetVehicleTypeByIdAsync(client, vehicle.TypeId);
                                                <span>@_type.Name</span>
                                            }
                                        }
                                    </td>
                                    <td>@vehicle.Description</td>
                                    <td>@vehicle.UserEmail</td>
                                    <td>
                                        @{
                                            switch (vehicle.Deleted)
                                            {
                                                case 0:
                                                    <center><span class="btn btn-xs btn-success">active</span></center>
                                                    break;
                                                case 1:
                                                    <center><span class="btn btn-xs btn-default">deleted</span></center>
                                                    break;
                                                default:
                                                    break;
                                            }
                                        }
                                    </td>
                                    <td>
                                        @{
                                            switch (vehicle.WriteHistory)
                                            {
                                                case 0:
                                                    <center><span class="btn btn-xs btn-danger">not run</span></center>
                                                    break;
                                                case 1:
                                                    <center><span class="btn btn-xs btn-info">running</span></center>
                                                    break;
                                                default:
                                                    break;
                                            }
                                        }
                                    </td>
                                    <td>
                                        <center>
                                            <a class="btn btn-xs btn-warning" href="@Url.Action("Edit", "Vehicle", new { numberPlate = vehicle.NumberPlate })" role="button">Sửa</a>
                                            <a class="btn btn-xs btn-danger" href="@Url.Action("Delete", "Vehicle", new { numberPlate = vehicle.NumberPlate })" role="button" onclick="return confirm('Bạn chắc chắn muốn xóa?')">Xóa</a>
                                        </center>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>